name: Music Mod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # ... (Download and Extract Forge MDK steps)

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run Gradle Setup Tasks
      run: ./gradlew setupDecompWorkspace --refresh-dependencies

    - name: Compile the Mod
      run: ./gradlew build

    # Try using @latest or a specific version
    - name: Upload Artifact
      uses: actions/upload-artifact@latest # Or actions/upload-artifact@v3.1.2
      with:
        name: MusicMod-1.0.0.jar
        path: forge-1.7.10-10.13.4.1614-1.7.10-mdk/build/libs/MusicMod-1.0.0.jar
